addSbtPlugin("com.typesafe.sbt"    % "sbt-git"               % "0.8.5")
addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph"  % "0.8.2")
addSbtPlugin("org.wartremover"     % "sbt-wartremover"       % "1.2.1")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"         % "1.5.0")
addSbtPlugin("pl.project13.scala"  % "sbt-jmh"               % "0.2.18")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"           % "0.3.0")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"           % "0.4.1")