addSbtPlugin("com.typesafe.sbt"    % "sbt-git"               % "0.8.5")
addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph"  % "0.8.2")
addSbtPlugin("org.brianmckenna"    % "sbt-wartremover"       % "0.14")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"         % "1.3.5")
addSbtPlugin("pl.project13.scala"  % "sbt-jmh"               % "0.2.11")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"           % "0.1.10")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"           % "0.4.1")